### ISSUE TITLE
DNS problem?

### ISSUE THREAD

**Issue by mslinn** [comtel2000/jfxvnc#1]
There must be a messed up DNS entry somewhere. If I click on the "View on Github" link on http://www.jfxvnc.org/ then the github page does not appear. If I instead enter the GitHub link (https://github.com/comtel2000/jfxvnc) into the URL address widget the proper page appears.

Tested on Firefox and Chrome in Windows

**Comment by comtel2000** [comment]
domain forward issue fixed
