### ISSUE TITLE
How to run the program?

### ISSUE THREAD

**Issue by mslinn** [comtel2000/jfxvnc#2]
The README makes no mention of how to run the program. I see you worked on a fork of [TigerVNC](https://github.com/comtel2000/tigervnc); is there any similarity?

**Comment by comtel2000** [comment]
The TigerVNC fork was a test how fast JavaFX UI can render images. JFxVNC is a new project starting from scratch with a alternative license to GPL.
Howto build and run without IDE will be pushed in the next few minutes.
